DROP TABLE IF EXISTS locales;

CREATE TABLE locales (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nomenclatura TEXT NOT NULL,
  location_id TEXT NOT NULL,
  lado TEXT,
  area TEXT,
  modulo TEXT,
  metraje REAL,
  metraje_original TEXT,
  area_comercial TEXT,
  nivel TEXT,
  estatus TEXT,
  situacion TEXT,
  marca TEXT,
  subdireccion TEXT,
  gerencia TEXT,
  giro_iata TEXT,
  giro_operativo TEXT,
  giro_indaabin TEXT,
  observaciones TEXT,
  fecha_formalizacion TEXT,
  fecha_conclusion TEXT,
  contract_number TEXT,
  contract_pending INTEGER DEFAULT 0,
  commercial_line TEXT,
  commercial_subline TEXT,
  cost_per_m2 REAL,
  monthly_rent REAL,
  participation_rate REAL,
  participation_notes TEXT,
  operations_start_date TEXT,
  signature_date TEXT,
  contract_term TEXT,
  renewal_date TEXT,
  guarantee_status TEXT,
  liability_policy_status TEXT,
  project_status TEXT,
  contract_status TEXT,
  operational_status TEXT,
  contact_data TEXT,
  manager TEXT,
  contract_stage TEXT,
  contract_source_sheet TEXT,
  contract_location_name TEXT,
  contract_location_id TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_locales_nomenclatura ON locales(nomenclatura);
CREATE INDEX idx_locales_location_id ON locales(location_id);
